# -*- coding: utf-8 -*-
"""data_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AW1p0lA4AdkKvNmX5DSX7hSp32o8HQVQ
"""

import pandas as pd
import numpy as np

df = pd.read_csv('202506-divvy-tripdata.csv')
df.head()

df.isnull().sum()
df.info()
df.duplicated().sum()

df = df.drop_duplicates()
df = df.dropna()
df.info()

df['started_at'] = pd.to_datetime(df['started_at'])
df['ended_at'] = pd.to_datetime(df['ended_at'])

df['ride_length'] = (df['ended_at'] - df['started_at']).dt.total_seconds()
df['day_of_week'] = df['started_at'].dt.day_name()
df['hour'] = df['started_at'].dt.hour

df = df[df['ride_length']> 0 ]

df.head()

avg_ride_user_type = df.groupby('member_casual')['ride_length'].mean()
print(avg_ride_user_type)

import matplotlib.pyplot as plt
plt.figure(figsize=(10,6))
avg_ride_user_type.plot(kind='bar', color=['green', 'orange'])
plt.title('Average Ride length: Member or casual')
plt.ylabel('Ride length')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

rides_by_day = df['day_of_week'].value_counts().reindex(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])
plt.figure(figsize=(10,6))
rides_by_day.plot(kind='bar', color=['coral'])
plt.title('Number of Rides by Day of the Week')
plt.xlabel('Day of the Week')
plt.ylabel('Number of Rides')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Count rides by starting hour
rides_by_hour = df['hour'].value_counts().sort_index()

# Plot
plt.figure(figsize=(10,5))
rides_by_hour.plot(kind='bar', color='steelblue')
plt.title('🕒 Rides by Hour of the Day')
plt.xlabel('Hour of Day (0-23)')
plt.ylabel('Number of Rides')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

summary_text=[]
summary_text.append(f"Total number of rides: {len(df)}")
summary_text.append(f"Average ride length: {df['ride_length'].mean():.2f} minutes")
summary_text.append(f"Maximum ride length: {df['ride_length'].max()} minutes")
summary_text.append(f"Minimum ride length: {df['ride_length'].min()} minutes")
summary_text.append(f"Most common day of the week for starting a ride: {df['day_of_week'].mode()[0]}")
summary_text.append(f"Most common hour of the day for starting a ride: {df['hour'].mode()[0]}")
with open('summary.txt', 'w') as f:
    for line in summary_text:
        f.write(line + '\n')

df.to_excel("cleaned_divvy_tripdata.xlsx", index=False)